# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

source ~/bin/dotfiles/bash/env
source ~/bin/dotfiles/bash/config
source ~/bin/dotfiles/bash/aliases

# Add /bin to PATH
export PATH=$PATH:~/bin

# RVM Info
[[ -s "/usr/local/lib/rvm" ]] && . "/usr/local/lib/rvm"

# If localrc exists, source it
if [ -f ~/localrc ]; then
	. ~/localrc
fi
