" Graphical Interfaces

set guifont=Bitstream\ Vera\ Sans:h20   	" Font family and font size.
set antialias		                        " MacVim: smooth fonts.
colorscheme vividchalk                      " Color for gVim
